## External Secret placeholder ##

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akv-external-secret-read-sp
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: akv-sp-secret-store
  target:
    name: external-secret-read-sp
  data:
  - secretKey: loginpw
    remoteRef:
      key: secret/loginPassword
  - secretKey: apiurl
    remoteRef:
      key: secret/apiUrl
  - secretKey: clientid
    remoteRef:
      key: secret/clientId
  - secretKey: clientsecret
    remoteRef:
      key: secret/clientSecret
  - secretKey: loginuname
    remoteRef:
      key: secret/loginUsername
  - secretKey: pullsecret
    remoteRef:
      key: secret/pullSecret

---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: akv-read-for-splunk-hec
#   namespace: openshift-logging
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: akv-cluster-secret
#   target:
#     name: hec-splunk-b64-secret
#   data:
#   - secretKey: <key in 'hec-splunk-b64-secret' object>
#     remoteRef:
#       key: secret/<secret key in akv>