## Read SP ##
apiVersion: v1
kind: Secret
metadata:
  name: akv-sp-read
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  ClientID: {{ .Values.rbac_roles.read_client_id }}  #service-principal-ID
  ClientSecret: {{ .Values.rbac_roles.read_client_secret }} #service-principal-secret

---
## Push SP ##
apiVersion: v1
kind: Secret
metadata:
  name: akv-sp-push
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  ClientID: {{ .Values.rbac_roles.write_client_id }}  #service-principal-ID
  ClientSecret: {{ .Values.rbac_roles.write_client_secret }} #service-principal-secret