###  ArgoCD tls config map for repository certs in all base gitops instances ###
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: argocd-tls-cm-policy
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-tls-cm-config
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                data:
                  gitlab.oidc.thecloudgarage.com: |
                    -----BEGIN CERTIFICATE-----
                    MIIDxzCCAq+gAwIBAgIUDM2TMcxQPCt4etk1b6XrmrE8PbMwDQYJKoZIhvcNAQEL
                    BQAwdTELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAk1IMQ8wDQYDVQQHDAZNdW1iYWkx
                    DjAMBgNVBAoMBXN0YWNrMQ8wDQYDVQQLDAZkZXZvcHMxJzAlBgNVBAMMHmdpdGxh
                    Yi5vaWRjLnRoZWNsb3VkZ2FyYWdlLmNvbTAeFw0yMjA4MjIxNDA4MjRaFw0yNDA4
                    MjExNDA4MjRaMHUxCzAJBgNVBAYTAklOMQswCQYDVQQIDAJNSDEPMA0GA1UEBwwG
                    TXVtYmFpMQ4wDAYDVQQKDAVzdGFjazEPMA0GA1UECwwGZGV2b3BzMScwJQYDVQQD
                    DB5naXRsYWIub2lkYy50aGVjbG91ZGdhcmFnZS5jb20wggEiMA0GCSqGSIb3DQEB
                    AQUAA4IBDwAwggEKAoIBAQDIHkS12bpLX7lE0Y1NHZnLqV3v2J0E2bvAqxsRdUK0
                    /duqytS4eUwGRdWbtAcAVe6uU0gehFMHhyw7/XccixG5x9rVoWn47bKkH4EDppxK
                    U0YHdpBur0mCNm0NbQSjMYRk7emkX/b6OMDSL96FGWEfhYq8FZwL3YVdKBJReLFa
                    Y8q9cY/zhKvjwFtfWEPqe4173tyOiwqAjU7RF9Yj8NaBFJnUiJCmb0fQZ0XXsNcU
                    UnPr4z4OvIDXQ9CcWXJXdc0cQJQhfkOGlhAKlVBhLR+Hx5pC8gsntWCN2UUkzd8M
                    xE4NsXN9+pQnLNaJmUtqyJySfGYLDbmhqQ6HGIoT/b+zAgMBAAGjTzBNMAsGA1Ud
                    DwQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATApBgNVHREEIjAggh5naXRsYWIu
                    b2lkYy50aGVjbG91ZGdhcmFnZS5jb20wDQYJKoZIhvcNAQELBQADggEBAMWUqIFr
                    UPHRlBzbHtDTnO0YlBe2UIfpnKcAxYuTeczB83kFGCa421SOV1lNsMJJT9OjrDfi
                    90QJXYClxCF/StcBOosTnSKbg7gli4QYGzVfXkGG6y4k8eHR3RvhfFXcgnXR8WGD
                    3fIBY7+kp1PZzBvwKlwzquS7XwR+0h9RA/8nzS06I6PzJ2jvKgnDGFzd3D9QfFJc
                    OKUtWEVjR2tVkKoAxv/PLy4QZsTuOskJ0VmBxGVS5mptCYRpfBlF113vrln2DML7
                    mSwKxUb55uFDoZY70W18nT+FA3ivTq2tNw5VAm/ANjmT3nwv4chTmMztA2X2zLQw
                    xxojcn1cssi6GTc=
                    -----END CERTIFICATE-----
                kind: ConfigMap
                metadata:
                  name: argocd-tls-certs-cm
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: argocd-tls-cm-policy-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    apps.open-cluster-management.io/reconcile-option: merge
placementRef:
  name: argocd-tls-cm-policy-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  ### Add argocd-tls-cm to placement
  - name: argocd-tls-cm-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: argocd-tls-cm-policy-placement
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift