apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/component: standalone
    app.kubernetes.io/instance: splunk-s1-standalone
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: standalone
    app.kubernetes.io/part-of: splunk-s1-standalone
    argocd.argoproj.io/instance: splunk-instance
  name: splunk-s1-standalone-service
  namespace: splunk
spec:
  host: splunk-s1-standalone-service-splunk.apps.dd-aro.eastus.aroapp.io
  port:
    targetPort: http-splunkweb
  tls:
    termination: edge
  to:
    kind: Service
    name: splunk-s1-standalone-service
    weight: 100
  wildcardPolicy: None