replicaCount: 1

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  tag: v0.9.12  #"v0.9.11-ubi"
installCRDs: true

crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
  createPushSecret: true
  conversion:
    enabled: true

leaderElect: false
controllerClass: ""
extendedMetricLabels: false
scopedNamespace: ""
scopedRBAC: false
processClusterExternalSecret: true
processClusterStore: true
processPushSecret: true
createOperator: true
concurrent: 1
serviceAccount:
  create: true
  automount: true

rbac:
  create: true
  servicebindings:
    create: true

podSecurityContext: {}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile: null

resources: {}

serviceMonitor:
  enabled: false
  namespace: ""
  interval: 30s
  scrapeTimeout: 25s
  honorLabels: false

metrics:
  listen:
    port: 8080
  service:
    enabled: false
    port: 8080

priorityClassName: ""
podDisruptionBudget:
  enabled: false
  minAvailable: 1
hostNetwork: false

webhook:
  create: true
  certCheckInterval: "5m"
  lookaheadInterval: ""
  replicaCount: 1
  revisionHistoryLimit: 10

  certDir: /tmp/certs
  failurePolicy: Fail
  hostNetwork: false
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: v0.9.12  #"v0.9.11-ubi"
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  port: 10250
  rbac:
    create: true
  serviceAccount:
    create: true
    automount: true

  certManager:
    enabled: false
    addInjectorAnnotations: true
    cert:
      create: true
      issuerRef:
        group: cert-manager.io
        kind: "Issuer"
        name: "my-issuer"
      duration: ""
      renewBefore: ""

  priorityClassName: ""
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  metrics:
    listen:
      port: 8080

    service:
      enabled: false
      port: 8080

  readinessProbe:
    address: ""
    port: 8081

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile: null
  resources: {}

certController:
  create: true
  requeueInterval: "5m"
  replicaCount: 1
  revisionHistoryLimit: 10

  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: v0.9.12  # "v0.9.11-ubi"
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  rbac:
    create: true
  serviceAccount:
    create: true
    automount: true

  hostNetwork: false
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  metrics:
    listen:
      port: 8080
    service:
      enabled: false
      port: 8080
      annotations: {}
  readinessProbe:
    address: ""
    port: 8081

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile: null

  controllerManager:
    startingCSV: external-secrets-operator.v0.9.11
    deploymentName: "external-secrets-operator-controller-manager"
    image:
      repository: "ghcr.io/external-secrets/external-secrets"
      pullPolicy: IfNotPresent
      tag: v0.9.12  #'v0.9.10'
