---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  namespace: openshift-logging
  name: instance
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  collection:
    logs:
      vector: {}
      type: vector
  curation:
    curator:
      schedule: 30 3 * * *
    type: curator
  logStore:
    lokistack:
      name: logging-loki
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      storage: {}
  managementState: Managed
  visualization:
    kibana:
      replicas: 1
    type: kibana
