
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ingress-secret-mirror-policy
  namespace: openshift-ingress
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-central-secret
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
              - rhacs-operator
              - stackrox
              - openshift-ingress
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  tls.crt: '{{ `{{hub fromSecret "openshift-ingress" "ngc-cert" "tls.crt" hub}}` }}'
                  tls.key: '{{ `{{hub fromSecret "openshift-ingress" "ngc-cert" "tls.key" hub}}` }}'
                kind: Secret
                metadata:
                  name: central-default-tls-cert
                  namespace: stackrox
                type: Opaque
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: ingress-secret-mirror-placement-binding
  namespace: openshift-ingress
placementRef:
  name: ingress-secret-mirror-secret-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: ingress-secret-mirror-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ingress-secret-mirror-secret-placement
  namespace: openshift-ingress
spec:
  # This will go to all managed clusters
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: local-cluster
        operator: In
        values:
          - 'true'
