# ## ClusterSecretStore - For Read
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: akv-cluster-secret-read
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   provider:
#     azurekv:
#       tenantId: {{ .Values.eso.tenant_id }}
#       vaultUrl: {{ .Values.eso.vault_url }}
#       authSecretRef:
#         clientId:
#           name: akv-sp-read
#           key: ClientID
#           namespace: {{ .Values.operator.namespace }}
#         clientSecret:
#           name: akv-sp-read
#           key: ClientSecret
#           namespace: {{ .Values.operator.namespace }}
# ---
# ## ClusterSecretStore - For Push
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: akv-cluster-secret-push
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   provider:
#     azurekv:
#       tenantId: {{ .Values.eso.tenant_id }}
#       vaultUrl: {{ .Values.eso.vault_url }}
#       authSecretRef:
#         clientId:
#           name: akv-sp-push
#           key: ClientID
#           namespace: {{ .Values.operator.namespace }}
#         clientSecret:
#           name: akv-sp-push
#           key: ClientSecret
#           namespace: {{ .Values.operator.namespace }}