## Placeholder for SecretStore

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akv-sp-secret-store
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.eso.tenant_id }}
      vaultUrl: {{ .Values.eso.vault_url }}
      authSecretRef:
        clientId:
          name: akv-sp-read
          key: ClientID
        clientSecret:
          name: akv-sp-read
          key: ClientSecret
